### ISSUE TITLE
A light version of the theme

### ISSUE THREAD

**Issue by kovdan01** [shvedes/telegram-gruvbox#1]
Thanks for your great job on creating an up-to-date version of gruvbox theme for Telegram! Are there any plans for also creating a light version of the theme? I suppose that you personally use a dark one, but, if support for the light variant is not too hard and time-consuming, it would be nice to have it as well.

**Comment by shvedes** [comment]
I can’t promise for sure, but as soon as I have time and desire, I’ll try to do it

**Comment by kovdan01** [comment]
@shvedes Thanks!

**Comment by shvedes** [comment]
@kovdan01 you are welcome
